### ISSUE TITLE
HTTPS for REST API

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-middleware#29]
The REST API is powered by express and it would be easy to add support for serving the API not only via HTTP but also HTTPS. This issue is about whether we need that or if we are planning to run the middleware behind a reverse proxy like NGINX or Apache that supports HTTPS anyways?

**Comment by ImmanuelSegol** [comment]
@michael1011 I think in the long term we would use NGINX anyways. @peartobear What do you think?

**Comment by michael1011** [comment]
Agreed. If we will use NGINX either way adding SSL to the express server is just unnecessary bloat.
